"""Generating and storing the package's opaque secrets.

Three kinds of credential pass through here, and the hash each gets is a
deliberate choice rather than a default:

* **Opaque high-entropy secrets** — authorization codes, refresh tokens,
  login session ids, machine-client secrets. Generated by
  :func:`new_secret`: 32 bytes from ``secrets.token_urlsafe``, i.e. 256 bits
  of CSPRNG entropy. Stored as the SHA-256 hex digest of the *exact* string
  (:func:`hash_secret`). A password KDF (argon2id) would be the wrong tool
  here: its cost exists to slow down guessing a *low*-entropy secret, and a
  256-bit random string cannot be guessed at any rate — while the KDF cost
  *would* be paid on every single token request, on the hot path of the
  refresh fan-out this SPEC has to survive. This is the same reasoning the
  MVP token store applies to the two halves of a ``plt_`` token
  (:mod:`palaia_hub.auth.store`), and it is standard practice for bearer
  credentials the server itself minted.
* **The owner's login password** — low entropy by nature, so argon2id, and
  specifically the *same* hasher the MVP token store uses
  (:mod:`palaia_hub.auth.hashing`) rather than a second argon2 configuration
  in the same process. See :mod:`palaia_hub.oauth.login`.
* **Nothing else.** No credential is ever persisted in a reversible form,
  and access tokens (JWTs) are not persisted at all.

Every comparison of a presented secret against a stored digest goes through
:func:`verify_hash`, which is :func:`secrets.compare_digest` — constant time
in the length of the digest, so a stored-digest comparison cannot be turned
into an oracle.
"""

from __future__ import annotations

import hashlib
import secrets

#: Bytes of entropy behind every opaque secret this package issues.
SECRET_BYTES = 32


def new_secret() -> str:
    """Return a fresh URL-safe secret with :data:`SECRET_BYTES` of entropy."""
    return secrets.token_urlsafe(SECRET_BYTES)


def hash_secret(secret: str) -> str:
    """Return the SHA-256 hex digest of ``secret`` (see the module docstring)."""
    return hashlib.sha256(secret.encode("utf-8")).hexdigest()


def verify_hash(secret: str, stored_hash: str) -> bool:
    """Constant-time-compare ``secret``'s digest against ``stored_hash``."""
    return secrets.compare_digest(hash_secret(secret), stored_hash)


__all__ = ["SECRET_BYTES", "hash_secret", "new_secret", "verify_hash"]
